package com.jole.ridetrackermobdev.controller;

import androidx.lifecycle.LiveData;

import com.jole.ridetrackermobdev.model.Ride;

import java.util.List;

public interface MainViewModelInterface {
    /**
     * Returns a List of all Rides
     * @return LiveData of a List
     */
    public LiveData<List<Ride>> getAllRides();

    /**
     * Returns the Data generated by the Service to be displayed in a UI
     * @return LiveData of a Double Array
     */
    public LiveData<double[]> getUiState();
}
